FROM    openjdk
WORKDIR usr/lib
ADD ./target/customerAuthentication-0.0.1-SNAPSHOT.jar /usr/lib/customerAuthentication-0.0.1-SNAPSHOT.jar
ENTRYPOINT  ["java","-jar","customerAuthentication-0.0.1-SNAPSHOT.jar"]